name: Auto-Version PWA on Deploy

# Temporarily disabled to resolve deployment issues
# on:
#   push:
#     branches: [ main, production ]
#   pull_request:
#     branches: [ main ]

on:
  workflow_dispatch: # Only run manually for now

jobs:
  auto-version-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full git history for version generation
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Auto-update PWA version
      run: |
        echo "🔄 Auto-updating PWA version for deployment..."
        node scripts/auto-version-update.js
        echo "PWA_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Commit version update (if on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sw.js package.json
        if git diff --staged --quiet; then
          echo "No version changes to commit"
        else
          git commit -m "🚀 Auto-update PWA version to ${{ env.PWA_VERSION }} [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Notify deployment
      if: success()
      run: |
        echo "✅ PWA version updated successfully!"
        echo "📱 Version: ${{ env.PWA_VERSION }}"
        echo "🔄 Vercel will auto-deploy from the updated commit"
        echo "🔄 Users will get update notifications within 30 seconds"